### ISSUE TITLE
Can't launch the Auto Update on my sd card (MacOs OSX 10.9.5)

### ISSUE THREAD

**Issue by aligato4444** [mattpannella/pocket_core_autoupdate_net#44]
I'm on an old Mac (10.9.5), I tried to install the Auto Updater on my SD Card but I've got this on my Terminal :

Last login: Wed Oct 19 08:10:26 on console
mbpdalburdajaud:~ albanbourdajaud$ /Volumes/Macintosh\ HD_2/Analogue\ POCKET/pocket_updater ; exit;
dyld: Symbol not found: _kSecAttrKeyTypeECSECPrimeRandom
  Referenced from: /Volumes/Macintosh HD_2/Analogue POCKET/pocket_updater
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Volumes/Macintosh HD_2/Analogue POCKET/pocket_updater
Trace/BPT trap: 5
logout

[Opération terminée]

Any ideas ?  (I'm french, sorry for my english)

**Comment by mattpannella** [comment]
the app is written using .net 6.0. you don't actually have to install the .net runtime on your Mac because I package all the files into the release, but it looks like it requires a minimum of Mac os 10.15, so unfortunately I'm not sure if it's going to work
https://learn.microsoft.com/en-us/dotnet/core/install/macos
